routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
/// Base routes ///
Route::get('/', 'HomeController@index')->name('home');
Route::get('/us', 'HomeController@us')->name('us');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/home', 'HomeController@index');
Route::get('/profile', 'HomeController@profile')->name('profile');

/// post routes ///
// ** Route::resource('post', 'PostController');
/* ||post *** Non-AuthRoute|| */
Route::prefix('post')->name('post.')->group(function () {
    Route::get('/', 'PostController@index')->name('index');
    /** ||post *** AuthRoute|| **/
    Route::middleware('auth')->group(function () {
        Route::get('/create', 'PostController@create')->name('create');
        Route::post('/create', 'PostController@store')->name('store');
        Route::get('/{post}/edit', 'PostController@edit')->name('edit');
        Route::put('/{post}/edit', 'PostController@update')->name('update');
        Route::delete('/{post}/edit', 'PostController@destroy')->name('destroy');
    //My Routes
        Route::get('/historial', 'PostController@historial')->name('history');
        Route::patch('/{post}/edit', 'PostController@toggle')->name('toggle');
        Route::get('/{post}/preview', 'PostController@preview')->name('preview');
    });
    Route::get('/{post}', 'PostController@show')->name('show');
});
/*  */
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/migrate', function () {
        Artisan::call('migrate',[
            '--seed' => true,
        ]);
        //
    })->name('migrar');
    Route::get('/migrate/fresh', function () {
        Artisan::call('migrate',[
            '--seed' => true,
        ]);
        //
    })->name('fresh');
    Route::get('/migrate/refresh', function () {
        Artisan::call('migrate:refresh',[
            '--seed' => true,
        ]);
        //
    })->name('refresh');
    Route::get('/storage-link', function () {
        Artisan::call('storage:link');
        //
    })->name('refresh');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('mobile-title')

@endsection

@section('content')
<section class="perfil">
    <article>
        <h3 class="title">{{ Auth::user()->name }}</h3>
        <h5 class="title">{{Auth::user()->email}}</h5>
        @if (Auth::user()->created_at)
        <h6 class="title">Miembro desde {{Auth::user()->created_at}}</h6>
        @endif
    </article>
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif
        @auth
        <article class="adminPanel">
            <a class="btn btn-invert" href="{{ route('admin.migrar') }}">Migrar</a>
            <br>
            <a class="btn btn-invert" href="{{ route('admin.refresh') }}">Refrescar</a>
            <br>
            <a class="btn btn-invert" href="{{ route('admin.fresh') }}">Romper todo</a>
        </article>
        @endauth
</section>
@endsection